### ISSUE TITLE
关于扫码登录显示的二维码疑似乱码无法扫描的问题

### ISSUE THREAD

**Issue by AnsonSkywalker** [shr-go/bili_live_tui#1]
[![xEvKCn.png](https://s1.ax1x.com/2022/09/26/xEvKCn.png)](https://imgse.com/i/xEvKCn)
（为了防止意料之外的隐私泄露，图片随手打了点码）
直接执行BAT脚本显示出的二维码是这个样子。实测使用小米官方应用商店下载的6.90.0版本B站客户端扫描二维码无论是贴着显示器还是拿远了扫描都没有任何反应。
操作系统是Windows 10 家庭中文版21H2内部版本号19044.2006。系统界面缩放比例是125%。
我自作聪明地在BAT中添加了chcp 65001，也试过手动以PowerShell运行启动命令，但显示出来的二维码也没什么区别。

**Comment by shr-go** [comment]
本地windows是在win11下测试的，我搞个对应版本的win10虚拟机试下

**Comment by AnsonSkywalker** [comment]
您好，我来小小地催更一下。
有考虑过更改一下编码方式甚至是更换二维码显示的方式吗？
据我所知用于社交平台机器人的[Onebot](https://github.com/botuniverse/onebot)适配器在扫码登录时使用的是生成、存放并显示一张PNG图片的方式。

**Comment by shr-go** [comment]
终端问题确实存在，花了一天也没有解决的的头绪hhh
所以目前是增加了输出二维码到目录的方法，可以扫描login.png完成登录
另外也可以安装windows terminal，应该是较老的终端对一些字符的支持不完善导致的

**Comment by AnsonSkywalker** [comment]
OK，1.2.0现在可以通过扫描二维码图片正常登录了。
咨询了一下我一个朋友，他的建议是.../internal/live_room/user_info.go里面func QRCodeLogin里生成二维码字符串时只要把调用ToSmallString直接换成ToString也许能解决问题。

**Comment by shr-go** [comment]
谢谢帮忙，这个方案的话，二维码显示太大了，会导致正常终端显示不全整个二维码

**Comment by AnsonSkywalker** [comment]
那就没什么了。我就等着后续跟进投喂打赏显示以及剩下的功能了。
